[package]
name = "const_base"
version = "0.1.0"
edition = "2018"

[dependencies]

[dev-dependencies.base64]
version = "0.13.0"
default_features = false

[dev-dependencies.rand]
version = "0.8"
default_features = false
features = ["small_rng"]

[dev-dependencies.itertools]
version = "0.10"
default_features = false





